name: CI Pipeline

on:
  push:
    branches:
      - main  # Trigger when pushing to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to main

jobs:
  build:
    runs-on: ubuntu-latest  # Runner environment (Linux)

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Action to checkout your code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Specify Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Run tests
        run: |
          pytest  # Run tests using pytest
